// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using ReCommand.API.EFData;
using ReCommand.API.EFData.Entities;
using System;

namespace ReCommand.API.Migrations
{
    [DbContext(typeof(ReCommandDbContext))]
    partial class ReCommandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("ReCommand.API.EFData.Entities.ProjectReCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("EnumReCommandType");

                    b.Property<string>("FinStage");

                    b.Property<string>("FromUserAvator");

                    b.Property<int>("FromUserId");

                    b.Property<string>("FromUserName");

                    b.Property<string>("Introduction");

                    b.Property<string>("ProjectAvator");

                    b.Property<int>("ProjectId");

                    b.Property<DateTime>("ReCommandTime");

                    b.Property<string>("Tags");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ProjectReCommands");
                });

            modelBuilder.Entity("ReCommand.API.EFData.Entities.ProjectReferenceUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProjectReCommandId");

                    b.Property<int>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("ProjectReCommandId");

                    b.ToTable("ProjectReferenceUsers");
                });

            modelBuilder.Entity("ReCommand.API.EFData.Entities.ProjectReferenceUser", b =>
                {
                    b.HasOne("ReCommand.API.EFData.Entities.ProjectReCommand")
                        .WithMany("ProjectReferenceUsers")
                        .HasForeignKey("ProjectReCommandId");
                });
#pragma warning restore 612, 618
        }
    }
}
